import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import DashboardSideBar from './(components)/DashboardSideBar'
import DashboardTopNav from './(components)/DashboardTopNav'
import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Platypus Sass',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const supabase = createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) {
    redirect('/auth/login')
  }
  return (
    <main className={cn('min-h-screen grid w-full lg:grid-cols-[280px_1fr]')}>
      <DashboardSideBar />
      <DashboardTopNav>
        <div className='p-4 flex flex-col gap-4 lg:gap-6'>{children}</div>
      </DashboardTopNav>
    </main>
  )
}
