import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import DashboardSideBar from './(components)/DashboardSideBar'
import DashboardTopNav from './(components)/DashboardTopNav'

export const metadata: Metadata = {
  title: 'Platypus Sass',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <main className={cn('min-h-screen grid w-full lg:grid-cols-[280px_1fr]')}>
      <DashboardSideBar />
      <DashboardTopNav>
        <div className='p-4 flex flex-col gap-4 lg:gap-6'>{children}</div>
      </DashboardTopNav>
    </main>
  )
}
