import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import DashboardSideBar from './(components)/DashboardSideBar'

export const metadata: Metadata = {
  title: 'Platypus Sass',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <main className={cn('min-h-screen grid w-full lg:grid-cols-[280px_1fr]')}>
      <DashboardSideBar />
      {children}
    </main>
  )
}
